# Config format schema number
format_version: 1

###################
## Model options
model_params:
  model_architecture: "arch_2dpass"

  input_dims: 4
  spatial_shape:
    - 1000
    - 1000
    - 70
  scale_list:
    - 2
    - 4
    - 8
    - 16
    - 16
    - 16

  hiden_size: 256
  num_classes: 17
  backbone_2d: resnet34
  pretrained2d: False

###################
## Dataset options
dataset_params:
  training_size: 28130
  dataset_type: "point_image_dataset_nus"
  pc_dataset_type: "nuScenes"
  collate_type: "collate_fn_default"
  ignore_label: 0
  label_mapping: "./config/label_mapping/nuscenes.yaml"

  # 2D augmentation
  resize:
    - 400
    - 240
  color_jitter:
    - 0.4
    - 0.4
    - 0.4
  flip2d: 0.5
  image_normalizer:
    - [0.485, 0.456, 0.406]
    - [0.229, 0.224, 0.225]
  max_volume_space:
    - 50
    - 50
    - 3
  min_volume_space:
    - -50
    - -50
    - -4

  train_data_loader:
    data_path: "./dataset/nuscenes/"
    batch_size: 8
    shuffle: True
    num_workers: 8
    rotate_aug: True
    flip_aug: True
    scale_aug: True
    transform_aug: True
    dropout_aug: True

  val_data_loader:
    data_path: "./dataset/nuscenes/"
    shuffle: False
    num_workers: 8

    # normal test
    batch_size: 8
    rotate_aug: False
    flip_aug: False
    scale_aug: False
    transform_aug: False
    dropout_aug: False

###################
## Train params
train_params:
  max_num_epochs: 80
  learning_rate: 0.24
  optimizer: SGD  # [SGD, Adam]
  lr_scheduler: CosineAnnealingLR  # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  momentum: 0.9
  nesterov: True
  weight_decay: 1.0e-4

  lambda_seg2d: 1
  lambda_xm: 0.05
  lambda_lovasz: 1
